//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchPack.Tests.ServiceUnits.Test.V1.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringContents {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringContents() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArchPack.Tests.ServiceUnits.Test.V1.Resources.StringContents", typeof(StringContents).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   新規登録 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddItem {
            get {
                return ResourceManager.GetString("AddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   部署 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BusinessUnit {
            get {
                return ResourceManager.GetString("BusinessUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取消 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CancelApplication {
            get {
                return ResourceManager.GetString("CancelApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変更 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   閉じる に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeleteItem {
            get {
                return ResourceManager.GetString("DeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   説明 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   明細一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DetailList {
            get {
                return ResourceManager.GetString("DetailList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ダウンロード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ヘッダー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   姓 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログイン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メール に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   次を検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NextSearch {
            get {
                return ResourceManager.GetString("NextSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   いいえ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   件中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OfCount {
            get {
                return ResourceManager.GetString("OfCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロール所属ユーザー編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RoleHeaderDetail {
            get {
                return ResourceManager.GetString("RoleHeaderDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロール一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RoleList {
            get {
                return ResourceManager.GetString("RoleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロール名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロール情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロール検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RoleSearhListInput {
            get {
                return ResourceManager.GetString("RoleSearhListInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロール所属ユーザー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RolesInUsers {
            get {
                return ResourceManager.GetString("RolesInUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索条件 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchCriteria {
            get {
                return ResourceManager.GetString("SearchCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   結果一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchResultList {
            get {
                return ResourceManager.GetString("SearchResultList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectItem {
            get {
                return ResourceManager.GetString("SelectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   次の に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TheNext {
            get {
                return ResourceManager.GetString("TheNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   件を表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToDisplayCount {
            get {
                return ResourceManager.GetString("ToDisplayCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   トップページ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TopPage {
            get {
                return ResourceManager.GetString("TopPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザー情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserInfo {
            get {
                return ResourceManager.GetString("UserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザー編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserInput {
            get {
                return ResourceManager.GetString("UserInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザー一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserList {
            get {
                return ResourceManager.GetString("UserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   所属ユーザー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザー名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザー情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザー検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserSearchList {
            get {
                return ResourceManager.GetString("UserSearchList", resourceCulture);
            }
        }
    }
}
