//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchPack.ServiceUnits.Shared.V1.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringContents {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringContents() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArchPack.ServiceUnits.Shared.V1.Resources.StringContents", typeof(StringContents).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 達成数.
        /// </summary>
        public static string AchieveCount {
            get {
                return ResourceManager.GetString("AchieveCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 達成率.
        /// </summary>
        public static string AchieveRate {
            get {
                return ResourceManager.GetString("AchieveRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アクション.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 実績工数.
        /// </summary>
        public static string ActualManHour {
            get {
                return ResourceManager.GetString("ActualManHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新規登録.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 追加.
        /// </summary>
        public static string AddItem {
            get {
                return ResourceManager.GetString("AddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基本情報.
        /// </summary>
        public static string Basic {
            get {
                return ResourceManager.GetString("Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求書.xls.
        /// </summary>
        public static string BillingFileName {
            get {
                return ResourceManager.GetString("BillingFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BillingTemplate.xls.
        /// </summary>
        public static string BillingTemplateFileName {
            get {
                return ResourceManager.GetString("BillingTemplateFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部署.
        /// </summary>
        public static string BusinessUnit {
            get {
                return ResourceManager.GetString("BusinessUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キャンセル.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string CancelApplication {
            get {
                return ResourceManager.GetString("CancelApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カテゴリ名.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 変更.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 閉じる.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ：.
        /// </summary>
        public static string Colon {
            get {
                return ResourceManager.GetString("Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 確認.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワードの確認.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 件を表示.
        /// </summary>
        public static string DataCount {
            get {
                return ResourceManager.GetString("DataCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 件中.
        /// </summary>
        public static string DataTotalCount {
            get {
                return ResourceManager.GetString("DataTotalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to トップページ.
        /// </summary>
        public static string DefaultPage {
            get {
                return ResourceManager.GetString("DefaultPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 削除.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 削除.
        /// </summary>
        public static string DeleteItem {
            get {
                return ResourceManager.GetString("DeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 納品書.xls.
        /// </summary>
        public static string DeliveryFileName {
            get {
                return ResourceManager.GetString("DeliveryFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeliveryTemplate.xls.
        /// </summary>
        public static string DeliveryTemplateFileName {
            get {
                return ResourceManager.GetString("DeliveryTemplateFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 説明.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 詳細.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 差分.
        /// </summary>
        public static string DiffHours {
            get {
                return ResourceManager.GetString("DiffHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 編集.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 実施日.
        /// </summary>
        public static string ExecutionDate {
            get {
                return ResourceManager.GetString("ExecutionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フリガナ（名）.
        /// </summary>
        public static string FirstNamePhonetic {
            get {
                return ResourceManager.GetString("FirstNamePhonetic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サーバーで予期しないシステムエラーが発生しました.
        /// </summary>
        public static string InternalServerErrorMessage {
            get {
                return ResourceManager.GetString("InternalServerErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ホームへ.
        /// </summary>
        public static string InternalServerErrorNavigationMessage {
            get {
                return ResourceManager.GetString("InternalServerErrorNavigationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to システムエラーが発生しました.
        /// </summary>
        public static string InternalServerErrorTitle {
            get {
                return ResourceManager.GetString("InternalServerErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 姓.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フリガナ（姓）.
        /// </summary>
        public static string LastNamePhonetic {
            get {
                return ResourceManager.GetString("LastNamePhonetic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログイン.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログアウト.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 電子メール.
        /// </summary>
        public static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理.
        /// </summary>
        public static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 月.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 月間目標.
        /// </summary>
        public static string MonthlyGoal {
            get {
                return ResourceManager.GetString("MonthlyGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 翌々月末日払い.
        /// </summary>
        public static string NextMonthAfterPayment {
            get {
                return ResourceManager.GetString("NextMonthAfterPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 翌月末日払い.
        /// </summary>
        public static string NextMonthPayment {
            get {
                return ResourceManager.GetString("NextMonthPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 次を検索.
        /// </summary>
        public static string NextSearch {
            get {
                return ResourceManager.GetString("NextSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to いいえ.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指定されたページはありません。.
        /// </summary>
        public static string NotFoundErrorMessage {
            get {
                return ResourceManager.GetString("NotFoundErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自動的にページが切り替わらない場合にはこのリンクをクリックしてください.
        /// </summary>
        public static string NotFoundErrorNavigationMessage {
            get {
                return ResourceManager.GetString("NotFoundErrorNavigationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指定されたページはありません。.
        /// </summary>
        public static string NotFoundErrorTitle {
            get {
                return ResourceManager.GetString("NotFoundErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to その他.
        /// </summary>
        public static string OtherPayment {
            get {
                return ResourceManager.GetString("OtherPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 担当者.
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワード.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 予定工数.
        /// </summary>
        public static string PlanManHour {
            get {
                return ResourceManager.GetString("PlanManHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 予定タスク.
        /// </summary>
        public static string PlanTask {
            get {
                return ResourceManager.GetString("PlanTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 予定週.
        /// </summary>
        public static string PlanWeek {
            get {
                return ResourceManager.GetString("PlanWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 役職.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 案件管理.
        /// </summary>
        public static string ProcessManagement {
            get {
                return ResourceManager.GetString("ProcessManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 案件検索.
        /// </summary>
        public static string ProcessSearch {
            get {
                return ResourceManager.GetString("ProcessSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プロファイル情報.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プロジェクト名.
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワード変更.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ロール所属ユーザー編集.
        /// </summary>
        public static string RoleHeaderDetail {
            get {
                return ResourceManager.GetString("RoleHeaderDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ロール名.
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ロール情報.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ロール検索.
        /// </summary>
        public static string RoleSearchListInput {
            get {
                return ResourceManager.GetString("RoleSearchListInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ロール所属ユーザー.
        /// </summary>
        public static string RolesInUsers {
            get {
                return ResourceManager.GetString("RolesInUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Apps/Sales/proto/FileTemplates.
        /// </summary>
        public static string SalesExcelTemplateUrl {
            get {
                return ResourceManager.GetString("SalesExcelTemplateUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検索.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検索条件.
        /// </summary>
        public static string SearchCriteria {
            get {
                return ResourceManager.GetString("SearchCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 結果一覧.
        /// </summary>
        public static string SearchResultList {
            get {
                return ResourceManager.GetString("SearchResultList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選択.
        /// </summary>
        public static string SelectItem {
            get {
                return ResourceManager.GetString("SelectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サービス.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 候補者管理.
        /// </summary>
        public static string StaffManagement {
            get {
                return ResourceManager.GetString("StaffManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 候補者検索.
        /// </summary>
        public static string StaffSearch {
            get {
                return ResourceManager.GetString("StaffSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サブカテゴリ名.
        /// </summary>
        public static string SubCategoryName {
            get {
                return ResourceManager.GetString("SubCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to システムエラー.
        /// </summary>
        public static string SystemError {
            get {
                return ResourceManager.GetString("SystemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目標達成数.
        /// </summary>
        public static string TargetAchieve {
            get {
                return ResourceManager.GetString("TargetAchieve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 対象月.
        /// </summary>
        public static string TargetMonth {
            get {
                return ResourceManager.GetString("TargetMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to タスク名.
        /// </summary>
        public static string TaskName {
            get {
                return ResourceManager.GetString("TaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 電話番号.
        /// </summary>
        public static string Tel {
            get {
                return ResourceManager.GetString("Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 送付状.xls.
        /// </summary>
        public static string TransmittalFileName {
            get {
                return ResourceManager.GetString("TransmittalFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransmittalTemplate.xls.
        /// </summary>
        public static string TransmittalTemplateFileName {
            get {
                return ResourceManager.GetString("TransmittalTemplateFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指定されたページを利用する権限がありません。.
        /// </summary>
        public static string UnauthorizedErrorMessage {
            get {
                return ResourceManager.GetString("UnauthorizedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自動的にページが切り替わらない場合にはこのリンクをクリックしてください.
        /// </summary>
        public static string UnauthorizedErrorNavigationMessage {
            get {
                return ResourceManager.GetString("UnauthorizedErrorNavigationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ページを利用する権限がありません.
        /// </summary>
        public static string UnauthorizedErrorTitle {
            get {
                return ResourceManager.GetString("UnauthorizedErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ユーザーID.
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ユーザー編集.
        /// </summary>
        public static string UserInput {
            get {
                return ResourceManager.GetString("UserInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ユーザー所属ロール.
        /// </summary>
        public static string UserInRoles {
            get {
                return ResourceManager.GetString("UserInRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ユーザー一覧.
        /// </summary>
        public static string UserList {
            get {
                return ResourceManager.GetString("UserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所属ユーザー.
        /// </summary>
        public static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ユーザー名.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ユーザー情報.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ユーザー検索.
        /// </summary>
        public static string UserSearchList {
            get {
                return ResourceManager.GetString("UserSearchList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作業週.
        /// </summary>
        public static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作業目標.
        /// </summary>
        public static string WeeklyGoal {
            get {
                return ResourceManager.GetString("WeeklyGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作業実績.
        /// </summary>
        public static string WeeklyResult {
            get {
                return ResourceManager.GetString("WeeklyResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 年.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to はい.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
